import test from "node:test";
import assert from "node:assert/strict";
import {company} from "../content/company";
import {contactDelivery} from "../lib/contact-delivery";
import {POST} from "../app/api/contact/route";
import {products} from "../content/products";
import {platformActions} from "../lib/platforms";
test("approved identity and dormant contact destination are centralized",()=>{assert.equal(company.legalName,"LLRD LLC");assert.equal(company.publicBrand,"LLRD LLC");assert.equal(company.jurisdiction,"Tennessee, USA");assert.equal(contactDelivery.recipient,"contactus@llrd.ai");assert.equal(contactDelivery.collectionEnabled,false);assert.equal(contactDelivery.privacyApproved,false);assert.equal(contactDelivery.provider,null);});
test("public contact collection is blocked before body parsing",async()=>{const result=await POST(new Request("https://llrd.ai/api/contact",{method:"POST",headers:{origin:"https://llrd.ai",host:"llrd.ai","content-type":"application/json"},body:"not JSON"}));assert.equal(result.status,503);assert.equal((await result.json()).ok,false);});
test("SONIE and ElseSide public destinations remain unavailable",()=>{for(const id of ["sonie","elseside"]){const product=products.find(p=>p.id===id)!;assert.equal(product.launchStatus,"COMING_SOON");assert.equal(product.webAppUrl,undefined);assert(platformActions(product).every(p=>!p.href));}});
