import {company} from "./company";
export interface InfoPage{title:string;eyebrow:string;intro:string;notice?:string;sections:{title:string;text:string}[];}
export const pages:Record<string,InfoPage>={
 about:{title:"Technology with people at its heart.",eyebrow:"ABOUT LLRD",intro:"LLRD Technologies brings a shared purpose to a growing portfolio: technology that connects what matters.",sections:[{title:"Company information",text:`${company.legalName} · ${company.jurisdiction}. Public brand: ${company.publicBrand}. This website continues to use the established LLRD Technologies identity.`},{title:"A company built around connection",text:"We believe useful technology begins by understanding people. Our work brings ideas, thoughtful design and practical utility together."},{title:"One purpose. Many possibilities.",text:"Our portfolio is designed to make room for different applications and needs. Every product can take its own path, while sharing the LLRD commitment to purposeful progress."}]},
 impact:{title:"What matters guides what we build.",eyebrow:"OUR IMPACT",intro:"People. Possibilities. Progress. Purpose. Four principles that shape how we think about technology.",notice:"These are our guiding principles. Published impact initiatives and measured outcomes will be shared when available.",sections:[]},
 support:{title:"A clear path to support.",eyebrow:"LLRD SUPPORT",intro:"Find support information for the LLRD product you use.",notice:"Product support details and verified contact channels are forthcoming. No support request is collected on this page.",sections:[{title:"Start with your product",text:"Each product page provides its own support and privacy links, alongside availability for web, iOS and Android."},{title:"Company enquiries",text:"For corporate contact information, visit the Contact page. Verified channels will be published there when available."}]},
 privacy:{title:"Your privacy matters.",eyebrow:"PRIVACY CENTER",intro:"A permanent home for LLRD corporate privacy information and product-specific policies.",notice:"Privacy policy information forthcoming. This page is a content shell and is not a finalized privacy policy.",sections:[{title:"Corporate privacy",text:"Reviewed information about data handling, retention, rights, contact details and applicable jurisdictions will be published here before public launch."},{title:"Product privacy",text:"Each application may handle different information. Refer to the policy for the specific product before using it."}]},
 security:{title:"Clarity builds confidence.",eyebrow:"SECURITY & TRUST",intro:"Find security information for LLRD Technologies and its applications.",notice:"Security information forthcoming. No certifications, regulatory approvals or compliance claims are asserted.",sections:[{title:"Product-specific information",text:"Security details will be published for each product after review. Practices and safeguards must be documented before they are described here."},{title:"Reporting a concern",text:"A verified channel for security reports and disclosure guidance is forthcoming. Do not submit sensitive information through unverified channels."}]},
 legal:{title:"Clear terms. Shared understanding.",eyebrow:"LEGAL",intro:"The home for LLRD corporate legal notices and product-specific terms.",notice:"Legal information forthcoming. This is not a finalized terms-of-service agreement.",sections:[{title:"Corporate notices",text:`${company.legalName}. Jurisdiction: ${company.jurisdiction}. Domain: llrd.ai. Intellectual property notices and website terms remain subject to legal review.`},{title:"Product terms",text:"Each product may have separate terms. Product pages will link to the applicable reviewed documents."}]},
 contact:{title:"Meaningful connections start here.",eyebrow:"CONTACT LLRD",intro:"For company enquiries, partnerships and conversations about LLRD Technologies.",notice:"Verified contact details are forthcoming. This page does not collect or send messages.",sections:[{title:"Looking for product help?",text:"Visit Support to find the appropriate product entry point."},{title:"Stay connected",text:"Approved contact and social channels will be published here when available."}]}
};
