/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=OperationsEnv types/operations-env.d.ts` (hash: b6dbb6e4d249b6dbe79d8e20b12fd2ef)
interface __BaseEnv_OperationsEnv {
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	MS_GRAPH_TENANT_ID: string;
	MS_GRAPH_CLIENT_ID: string;
	LLRD_CONTACT_PROVIDER: string;
	LLRD_AI_ENABLED: string;
	LLRD_AI_PROVIDER: string;
	LLRD_AI_MODEL: string;
	LLRD_AI_FREE_PLAN_CONFIRMED: string;
	LLRD_LOCAL_STUDIO: string;
	SITE_INDEXABLE: string;
	LLRD_AI_TRUSTED_IP_HEADER: string;
	LLRD_AI_ACCEPTANCE_RUN: string;
	OPS_ENABLED: string;
	OPS_TIMEZONE: string;
	OPS_INITIAL_REPORT_ID: string;
	SITE_QUOTA: DurableObjectNamespace /* SiteQuota */;
	OPERATIONS: DurableObjectNamespace /* OperationsMonitor */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_OperationsEnv {}
}
interface OperationsEnv extends __BaseEnv_OperationsEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MS_GRAPH_TENANT_ID" | "MS_GRAPH_CLIENT_ID" | "LLRD_CONTACT_PROVIDER" | "LLRD_AI_ENABLED" | "LLRD_AI_PROVIDER" | "LLRD_AI_MODEL" | "LLRD_AI_FREE_PLAN_CONFIRMED" | "LLRD_LOCAL_STUDIO" | "SITE_INDEXABLE" | "LLRD_AI_TRUSTED_IP_HEADER" | "LLRD_AI_ACCEPTANCE_RUN" | "OPS_ENABLED" | "OPS_TIMEZONE" | "OPS_INITIAL_REPORT_ID">> {}
}
