import Image from "next/image";
import {RotatingEarth} from "@/components/EarthCanvas";
import {DiscoveryEntry} from "@/components/DiscoveryEntry";
import {company} from "@/content/company";
import {brand} from "@/content/brand";
import {orderedProducts} from "@/content/products";
import {trustLinks} from "@/content/navigation";
import {Button,SectionHeader,TrustLink,Statement} from "@/components/ui";
import {ProductCard} from "@/components/ProductCard";
import {pageMetadata} from "@/lib/seo";
export const metadata=pageMetadata(company.name,company.description,"/");
export default function Home(){const featured=orderedProducts().filter(p=>p.featured);return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Organization",name:company.name,legalName:company.legalName,alternateName:company.publicBrand,url:company.domain,slogan:company.tagline}).replace(/</g,"\\u003c")}}/>
<section className="hero hero-technical">{brand.earthSunrise&&<Image className="hero-earth" src={brand.earthSunrise} alt={brand.heroAlt} fill priority sizes="100vw"/>}<RotatingEarth/><div className="hero-shade" aria-hidden="true"/><div className="hero-content container"><div className="hero-overline"><p className="eyebrow">LLRD TECHNOLOGIES</p><span className="technical-label">PEOPLE / TECHNOLOGY / CONNECTION</span></div><h1><span className="hero-first-line">Technology that connects</span><em>what matters.</em></h1><div className="hero-bottom"><p>{company.description}</p><Button href="/products">Explore our products</Button></div><div className="hero-rule" aria-hidden="true"/><div className="hero-caption"><span>PEOPLE · POSSIBILITIES · PROGRESS · PURPOSE</span><a href="#portfolio">DISCOVER LLRD <span aria-hidden="true">↓</span></a></div></div></section>
<section id="portfolio" className="section container portfolio-intro"><SectionHeader eyebrow="OUR PORTFOLIO" title="Technology built around real life."><TrustLink href="/products">All products</TrustLink></SectionHeader><p className="lead">From family history and health to learning, entertainment, and the ideas still ahead.</p>{featured.length?<div className="card-grid">{featured.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className="portfolio-empty"><div className="portfolio-number" aria-hidden="true">LLRD</div><div><p className="eyebrow">FEATURED PRODUCTS</p><h3>A place for what comes next.</h3><p>Discover LLRD applications here as they become available, with clear ways to access each one.</p><TrustLink href="/products">Explore the portfolio</TrustLink></div></div>}<DiscoveryEntry/></section>
<section className="section container company-progress"><div><p className="eyebrow">FROM THE COMPANY</p><h2>Follow what comes next.</h2><p>Product news and development updates from across LLRD.</p><TrustLink href="/updates">Read our updates</TrustLink></div><div><p className="eyebrow">PARTNER WITH LLRD</p><h2>Build a connection.</h2><p>Have an idea for a product pilot, distribution opportunity, or technology collaboration? Let’s start a conversation.</p><TrustLink href="/contact">Discuss a partnership</TrustLink></div></section><section className="why-section"><div className="container split"><div><p className="eyebrow">WHY LLRD</p><h2>It starts with<br/><em>what matters to you.</em></h2></div><div><p className="lead">{company.why}</p><TrustLink href="/about">Get to know LLRD</TrustLink></div></div></section>
<section className="trust-section"><div className="container"><p className="eyebrow">BUILT ON TRUST</p><Statement>Connection begins<br/>with confidence.</Statement><p>A clear place to find privacy, security and legal information for LLRD and its products.</p><div className="trust-links">{trustLinks.map(l=><TrustLink key={l.href} href={l.href}>{l.label}</TrustLink>)}</div></div></section>
</>;}
