"use client";
import Link from 'next/link';
import {useState,type FormEvent} from 'react';
import {contactOptions,privacyOptions,validateInquiry,type Inquiry} from '@/lib/contact';
export function ContactInquiry({privacy=false}:{privacy?:boolean}){
 const [data,setData]=useState<Inquiry>({name:'',email:'',service:privacy?'Other privacy request':'',message:'',website:''});const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);
 const update=(key:keyof Inquiry,value:string)=>setData(d=>({...d,[key]:value}));
 async function submit(e:FormEvent){e.preventDefault();const result=validateInquiry(data);if(Object.keys(result.errors).length){setStatus(Object.values(result.errors).join(' '));return;}setBusy(true);try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(result.data),signal:AbortSignal.timeout(15000)});const p=await r.json();setStatus(r.ok&&p.ok===true?'Your inquiry has been received.':p.message||'Your inquiry has not been sent.');}catch{setStatus('We could not confirm delivery. Your entries remain here.');}finally{setBusy(false);}}
 return <section id="inquiry" className="contact-inquiry"><div><p className="eyebrow">LET’S CONNECT</p><h2>{privacy?"Your privacy choices":"Send an inquiry."}</h2><p>General questions, privacy, legal notices, accessibility and copyright matters all reach the same LLRD mailbox.</p></div><form onSubmit={submit} aria-label={privacy?"Privacy request":"Business inquiry"} aria-busy={busy}><div className="inquiry-field"><label htmlFor="name">Name</label><input id="name" required maxLength={100} autoComplete="name" value={data.name} onChange={e=>update('name',e.target.value)}/></div><div className="inquiry-field"><label htmlFor="email">Email address</label><input id="email" required type="email" maxLength={254} autoComplete="email" value={data.email} onChange={e=>update('email',e.target.value)}/></div><div className="inquiry-field"><label htmlFor="service">Inquiry category</label><select id="service" required value={data.service} onChange={e=>update('service',e.target.value)}><option value="">Choose a category</option>{(privacy?privacyOptions:contactOptions).map(c=><option key={c}>{c}</option>)}</select></div><div className="inquiry-field"><label htmlFor="message">Message</label><textarea id="message" required rows={6} maxLength={5000} aria-describedby="sensitive-notice" value={data.message} onChange={e=>update('message',e.target.value)}/><p id="sensitive-notice" className="inquiry-note">Please do not submit passwords, financial information, health information, genetic information, government identification numbers, or other highly sensitive personal information through this form.</p></div><div hidden aria-hidden="true"><label htmlFor="website">Leave empty</label><input id="website" tabIndex={-1} autoComplete="off" value={data.website} onChange={e=>update('website',e.target.value)}/></div><p className="inquiry-note">Information submitted through this form will be used to respond to your inquiry, provide requested information, maintain appropriate business records, and protect our services. <Link href="/privacy">Privacy Policy</Link></p><p className="delivery-note">Online delivery is not connected yet. Please use the contact details above. Preparing this form does not send an inquiry.</p><button className="button" disabled={busy}>{busy?'Checking…':'Submit inquiry'}</button><p role="status">{status}</p></form></section>;
}
