"use client";
import Image from "next/image";
import type {Product} from "@/content/products";
import {internalAttribution} from "@/lib/attribution";
import {track} from "@/lib/analytics";
import {ProductPlatformCTA} from "./ProductPlatformCTA";
export function DiscoveryRecommendations({products,interest,search,campaignId,onLeave,topic}:{topic?:string;products:readonly Product[];interest:string;search:string;campaignId?:string;onLeave:()=>void}){
 return <div className="discovery-results">{products.length?products.map(p=><article className="discovery-result" data-product={p.id} key={p.id}><p className="eyebrow">{p.launchStatus==="COMING_SOON"?"COMING SOON":p.category}</p>{p.logo&&<div className="discovery-brand" data-product={p.id}><Image src={p.logo} alt={p.name+" logo"} width={320} height={107} style={{objectFit:"contain"}}/></div>}<h3>{p.name}</h3><p className="discovery-tagline">{p.tagline}</p><h4>Why it may be right for you</h4><p>{p.id==="sonie" ? `${topic ? "You want to " + ({history:"explore your family history",stories:"preserve family stories",relatives:"connect with relatives",tree:"understand your family tree",memories:"save family memories"} as Record<string,string>)[topic] : "You’re interested in family and memories"}. SONIE is being built around the people, memories and stories that connect generations.` : `You chose ${interest.toLowerCase()}. ElseSide™ is being developed for players drawn to discovery, exploration, mystery and story-driven interactive worlds.`}</p><a className="button" href={internalAttribution("/products/"+p.slug,search)} onClick={()=>{track("product_selected",{productId:p.id,campaignId});track("learn_more_selected",{productId:p.id,campaignId});onLeave();}}>Learn More <span aria-hidden="true">↗</span></a><div className="discovery-channels"><ProductPlatformCTA product={p} campaignId={campaignId} headingLevel={4}/></div></article>):<div className="notice"><h3>More possibilities are ahead.</h3><p>We don’t have a matching product to share yet. Explore the portfolio to see what we’re building.</p></div>}</div>;
}
