import {operations} from '../../config/operations-monitoring';
export type Level='GREEN'|'YELLOW'|'RED';
export type Check={name:string;level:Level;evidence:string;ms?:number};
export type Metric={kind:'contact'|'ai';status:number;ms:number};
export type Counts=Record<string,number>;
export type Report={at:string;date:string;level:Level;checks:Check[];counts:Counts;trends:Record<string,unknown>;generated:boolean;emailAccepted:boolean;deliveryVerified:'NOT AVAILABLE';sendState:string};
export function localDate(now:number,tz:string=operations.timezone){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(now);const get=(t:string)=>parts.find(p=>p.type===t)?.value;return {date:`${get('year')}-${get('month')}-${get('day')}`,hour:Number(get('hour'))};}
export function expiry(iso:string|undefined,now=Date.now()):Check{if(!iso||!Number.isFinite(Date.parse(iso)))return {name:'Microsoft credential expiry',level:'YELLOW',evidence:'NOT CONFIGURED: owner must provide the expiration date, not the secret.'};const days=Math.ceil((Date.parse(iso)-now)/86400000);const threshold=operations.expiryDays.filter(n=>days<=n).at(-1);return {name:'Microsoft credential expiry',level:days<=0?'RED':days<=90?'YELLOW':'GREEN',evidence:`${days} days remaining${threshold?`; ${threshold}-day warning threshold`:''}. No automatic rotation.`};}
export function addMetric(c:Counts,m:Metric){if(!['ai','contact'].includes(m.kind)||!Number.isInteger(m.status)||m.status<100||m.status>599)return c;const result={...c};const inc=(key:string,n=1)=>result[key]=(result[key]||0)+n;inc(`${m.kind}.attempts`);inc(`${m.kind}.http.${m.status}`);inc(`${m.kind}.durationMs`,Math.max(0,Math.min(60000,Math.round(m.ms)||0)));if(m.status>=200&&m.status<300)inc(`${m.kind}.accepted`);if(m.status>=500)inc(`${m.kind}.failures`);if([400,413,415,422].includes(m.status))inc(`${m.kind}.validation`);if(m.status===429)inc(`${m.kind}.throttled`);return result;}
export function severity(checks:Check[]):Level{return checks.some(c=>c.level==='RED')?'RED':checks.some(c=>c.level==='YELLOW')?'YELLOW':'GREEN';}
export function recommendations(checks:Check[]){return checks.filter(c=>c.level!=='GREEN').map(c=>({priority:c.level==='RED'?'High':'Medium',category:c.name,evidence:c.evidence,action:`Review and resolve ${c.name}; verify the next measurement.`,impact:'Restore verified operation or close a monitoring gap.',effort:'Small / assess after review',ownerApprovalRequired:true}));}
export async function boundedText(r:Response,limit:number=operations.maxBodyBytes){const reader=r.body?.getReader();if(!reader)return '';let text='',bytes=0;const decoder=new TextDecoder();while(true){const v=await reader.read();if(v.done)break;bytes+=v.value.byteLength;if(bytes>limit){await reader.cancel();throw new Error('body_limit');}text+=decoder.decode(v.value,{stream:true});}return text+decoder.decode();}
export function sitemapUrls(xml:string){if(!/<urlset[\s>]/i.test(xml)||!/<\/urlset>/i.test(xml))throw new Error('invalid_sitemap');return [...xml.matchAll(/<loc>\s*([^<]+)\s*<\/loc>/gi)].map(m=>m[1].trim().replaceAll('&amp;','&')).filter(u=>{try{return new URL(u).origin===operations.site;}catch{return false;}}).slice(0,operations.crawlLimit);}
export function seo(html:string){const meta=(name:string)=>{const tags=html.match(/<meta\b[^>]*>/gi)||[];return tags.find(t=>new RegExp(`(?:name|property)=["']${name}["']`,'i').test(t))?.match(/content=["']([^"']*)/i)?.[1]||'';};return {title:html.match(/<title[^>]*>([^<]*)<\/title>/i)?.[1]||'',description:meta('description'),canonical:html.match(/<link[^>]*rel=["']canonical["'][^>]*href=["']([^"']+)/i)?.[1]||'',noindex:/noindex/i.test(meta('robots')),openGraph:!!meta('og:title'),structuredData:/application\/ld\+json/i.test(html)};}
export function robotsAllows(text:string){let applies=false;for(const raw of text.split('\n')){const line=raw.split('#')[0].trim();if(/^user-agent:/i.test(line))applies=/^user-agent:\s*\*$/i.test(line);if(applies&&/^disallow:\s*\/$/i.test(line))return false;}return /user-agent:/i.test(text);}
export async function health(url:string,request:typeof fetch=fetch){const start=Date.now();try{const r=await request(url,{redirect:'manual',signal:AbortSignal.timeout(operations.timeoutMs),headers:{'User-Agent':'LLRD-Operations/1.0'}});const text=await boundedText(r);return {status:r.status,ms:Date.now()-start,text,noindex:/noindex/i.test(r.headers.get('x-robots-tag')||''),location:r.headers.get('location')};}catch{return {status:0,ms:Date.now()-start,text:'',noindex:false,location:null};}}
export function renderReport(r:Report){return [`LLRD Daily Operations Report — ${r.date} — ${r.level}`,'','EXECUTIVE STATUS',`Overall: ${r.level}`,`Period: previous 24 hours ending ${r.at}. Measurements begin when monitoring is installed; missing data is not zero.`,...r.checks.map(c=>`${c.name}: ${c.level} — ${c.evidence}`),'','CONTACT / AI AGGREGATE COUNTS',JSON.stringify(r.counts),'','7 / 30 / 90-DAY TRENDS (weekly/monthly reviews included)',JSON.stringify(r.trends),'','RECOMMENDATIONS',...recommendations(r.checks).map(x=>`${x.priority} | ${x.category}\nEvidence: ${x.evidence}\nAction: ${x.action}\nImpact: ${x.impact}\nEffort: ${x.effort}\nOwner approval required: Yes`),'','REPORT GENERATED: YES','EMAIL ACCEPTED: recorded after provider response','EMAIL DELIVERY VERIFIED: NOT AVAILABLE','No inquiry bodies, visitor identifiers, or credentials are included.'].join('\n');}
