import {operations} from '../../config/operations-monitoring';
import {boundedText,type Check} from './core';
// Optional read-only adapters. No provider response bodies, URLs containing keys, or tokens are logged.
export async function integrations(env:Record<string,string|undefined>,request:typeof fetch=fetch):Promise<Check[]>{
 const checks:Check[]=[];const missing=(name:string)=>checks.push({name,level:'YELLOW',evidence:'OWNER AUTH REQUIRED; no data collected and no sitemap submitted.'});
 if(env.GSC_CLIENT_ID&&env.GSC_CLIENT_SECRET&&env.GSC_REFRESH_TOKEN){try{
  const auth=await request('https://oauth2.googleapis.com/token',{method:'POST',signal:AbortSignal.timeout(8000),body:new URLSearchParams({client_id:env.GSC_CLIENT_ID,client_secret:env.GSC_CLIENT_SECRET,refresh_token:env.GSC_REFRESH_TOKEN,grant_type:'refresh_token'})});
  const token=JSON.parse(await boundedText(auth,32000)) as {access_token?:string};if(!auth.ok||!token.access_token)throw new Error('auth');
  const property=env.GSC_PROPERTY||operations.integrations.googleProperty;
  if(!['https://llrd.ai/','sc-domain:llrd.ai'].includes(property))throw new Error('property');
  for(const days of [7,28,90]){const end=Date.now()-3*86400000;const r=await request(`https://www.googleapis.com/webmasters/v3/sites/${encodeURIComponent(property)}/searchAnalytics/query`,{method:'POST',signal:AbortSignal.timeout(8000),headers:{Authorization:`Bearer ${token.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({startDate:new Date(end-days*86400000).toISOString().slice(0,10),endDate:new Date(end).toISOString().slice(0,10),rowLimit:1})});const data=JSON.parse(await boundedText(r,32000)) as {rows?:{clicks:number;impressions:number;ctr:number;position:number}[]};if(!r.ok)throw new Error('api');const row=data.rows?.[0];checks.push({name:`Google Search ${days}d`,level:'GREEN',evidence:row?`Clicks ${Number(row.clicks)}, impressions ${Number(row.impressions)}, CTR ${Number(row.ctr)}, average position ${Number(row.position)}. Data ends three days ago.`:'Connected; no rows returned (not evidence of index exclusion).'});}
 }catch{checks.push({name:'Google Search Console',level:'YELLOW',evidence:'Authentication, permission, or API response unavailable; no response body retained.'});}}else missing('Google Search Console');
 if(env.BING_WEBMASTER_API_KEY){try{const u=new URL('https://ssl.bing.com/webmaster/api.svc/json/GetRankAndTrafficStats');u.searchParams.set('siteUrl',operations.integrations.bingSite);u.searchParams.set('apikey',env.BING_WEBMASTER_API_KEY);const r=await request(u,{signal:AbortSignal.timeout(8000)});const d=JSON.parse(await boundedText(r,100000)) as {d?:{Clicks?:number;Impressions?:number}[]};if(!r.ok||!Array.isArray(d.d))throw new Error('api');checks.push({name:'Bing Webmaster',level:'GREEN',evidence:`${d.d.length} returned daily rows; clicks ${d.d.reduce((n,v)=>n+(Number(v.Clicks)||0),0)}; impressions ${d.d.reduce((n,v)=>n+(Number(v.Impressions)||0),0)}. Sitemap submission remains owner-verified.`});}catch{checks.push({name:'Bing Webmaster',level:'YELLOW',evidence:'API unavailable; no request URL or response body retained.'});}}else missing('Bing Webmaster');
 if(env.OPS_CF_ANALYTICS_TOKEN){try{const r=await request('https://api.cloudflare.com/client/v4/graphql',{method:'POST',signal:AbortSignal.timeout(8000),headers:{Authorization:`Bearer ${env.OPS_CF_ANALYTICS_TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify({query:'query($account: string, $start: string, $end: string) { viewer { accounts(filter: {accountTag: $account}) { workersInvocationsAdaptive(limit: 100, filter: {scriptName: "llrdai", datetime_geq: $start, datetime_leq: $end}) { sum { requests errors subrequests } } } } }',variables:{account:'4ee8decdf0276e41146ec38968ac1d41',start:new Date(Date.now()-86400000).toISOString(),end:new Date().toISOString()}})});const d=JSON.parse(await boundedText(r,100000)) as {errors?:unknown;data?:{viewer:{accounts:{workersInvocationsAdaptive:{sum:{requests:number;errors:number;subrequests:number}}[]}[]}}};const rows=d.data?.viewer.accounts[0]?.workersInvocationsAdaptive;if(!r.ok||d.errors||!rows)throw new Error('api');checks.push({name:'Cloudflare Worker analytics',level:rows.some(x=>x.sum.errors>0)?'YELLOW':'GREEN',evidence:`Sampled 24h totals: requests ${rows.reduce((n,x)=>n+x.sum.requests,0)}, errors ${rows.reduce((n,x)=>n+x.sum.errors,0)}. Not unique visitors.`});}catch{checks.push({name:'Cloudflare Worker analytics',level:'YELLOW',evidence:'Analytics API unavailable or permission/plan limitation.'});}}else missing('Cloudflare Worker analytics');
 return checks;
}
